const fireEmblemClasses = [
    {
      "Class Name": "Fighter",
      "Certification": "Axe D, Bow D, Brawl D",
      "Level Seal": "Beginner",
      "Proficiency": "Axe +1, Bow +1, Brawl +1",
      "Abilities": "",
      "Mastery Abilities": "Shove, Strength + 2",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Monk",
      "Certification": "Reason D, Faith D",
      "Level Seal": "Beginner",
      "Proficiency": "Faith +1, Reason +1",
      "Abilities": "",
      "Mastery Abilities": "Draw Back, Magic +2",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Myrmidon",
      "Certification": "Sword D",
      "Level Seal": "Beginner",
      "Proficiency": "Sword +1",
      "Abilities": "",
      "Mastery Abilities": "Speed +2, Swap",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Soldier",
      "Certification": "Lance D",
      "Level Seal": "Beginner",
      "Proficiency": "Lance +1",
      "Abilities": "",
      "Mastery Abilities": "Defense +2, Reposition",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Archer",
      "Certification": "Bow C",
      "Level Seal": "Intermediate",
      "Proficiency": "Bow +2, Sword +1",
      "Abilities": "Bowrange +1",
      "Mastery Abilities": "Hit +20",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Armored Knight",
      "Certification": "Axe C, Heavy Armor D",
      "Level Seal": "Intermediate",
      "Proficiency": "Axe +2, Hvy Armor +2, Lance +1",
      "Abilities": "",
      "Mastery Abilities": "Armored Blow",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Brawler",
      "Certification": "Brawl C",
      "Level Seal": "Intermediate",
      "Proficiency": "Axe +1, Brawl +2",
      "Abilities": "Unarmed Combat",
      "Mastery Abilities": "Unarmed Combat",
      "Magic": "No",
      "Specific": "Male only",
    },
    {
      "Class Name": "Brigand",
      "Certification": "Axe C",
      "Level Seal": "Intermediate",
      "Proficiency": "Axe +2, Brawl +1",
      "Abilities": "",
      "Mastery Abilities": "Death Blow",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Cavalier",
      "Certification": "Lance C, Riding D",
      "Level Seal": "Intermediate",
      "Proficiency": "Lance +2, Riding +2, Sword +1",
      "Abilities": "Canto",
      "Mastery Abilities": "Desperation",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Dark Mage",
      "Certification": "Reason C, Dark Seal",
      "Level Seal": "Intermediate",
      "Proficiency": "Faith +1, Reason +2",
      "Abilities": "Heartseeker, Miasma",
      "Mastery Abilities": "Poison Strike",
      "Magic": "Yes",
      "Specific": "Male only",
    },
    {
      "Class Name": "Mage",
      "Certification": "Reason C",
      "Level Seal": "Intermediate",
      "Proficiency": "Faith +1, Reason +2",
      "Abilities": "Fire",
      "Mastery Abilities": "Fiendish Blow",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Mercenary",
      "Certification": "Sword C",
      "Level Seal": "Intermediate",
      "Proficiency": "Axe +1, Sword +2",
      "Abilities": "",
      "Mastery Abilities": "Vantage",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Pegasus Knight",
      "Certification": "Lance C, Flying D",
      "Level Seal": "Intermediate",
      "Proficiency": "Flying +2, Lance +2, Sword +1",
      "Abilities": "Avo +10, Canto",
      "Mastery Abilities": "Darting Blow, Triangle Attack",
      "Magic": "No",
      "Specific": "Female only",
    },
    {
      "Class Name": "Priest",
      "Certification": "Faith C",
      "Level Seal": "Intermediate",
      "Proficiency": "Faith +2, Reason +1",
      "Abilities": "Heal, White Magic Heal +5",
      "Mastery Abilities": "Miracle",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Thief",
      "Certification": "Sword C",
      "Level Seal": "Intermediate",
      "Proficiency": "Bow +1, Sword +2",
      "Abilities": "Locktouch, Steal",
      "Mastery Abilities": "Steal",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Bow Knight",
      "Certification": "Lance C, Bow A, Riding A",
      "Level Seal": "Master",
      "Proficiency": "Bow +3, Lance +3, Riding +3",
      "Abilities": "Bowfaire, Bowrange +2, Canto",
      "Mastery Abilities": "Defiant Spd",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Dark Knight",
      "Certification": "Lance C, Reason B+, Riding A",
      "Level Seal": "Master",
      "Proficiency": "Lance +3, Reason +3, Riding +3",
      "Abilities": "Black Tomefaire, Canto, Dark Tomefaire",
      "Mastery Abilities": "Seal Resistance",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Falcon Knight",
      "Certification": "Sword C, Lance A, Flying B+",
      "Level Seal": "Master",
      "Proficiency": "Flying +3, Lance +3, Sword +3",
      "Abilities": "Avo +10, Canto, Lancefaire",
      "Mastery Abilities": "Defiant Avo",
      "Magic": "No",
      "Specific": "Female only",
    },
    {
      "Class Name": "Great Knight",
      "Certification": "Axe B+, Heavy Armor A, Riding B+",
      "Level Seal": "Master",
      "Proficiency": "Axe +3, Hvy Armor +3, Lance +3",
      "Abilities": "Axefaire, Canto, Lancefaire",
      "Mastery Abilities": "Defiant Def",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Gremory",
      "Certification": "Reason A, Faith A",
      "Level Seal": "Master",
      "Proficiency": "Faith +3, Reason +3",
      "Abilities": "Black Magic Uses x2, Dark Magic Uses x2, White Magic Uses x2",
      "Mastery Abilities": "Defiant Mag",
      "Magic": "Yes",
      "Specific": "Female only",
    },
    {
      "Class Name": "Holy Knight",
      "Certification": "Lance C, Faith B+, Riding A",
      "Level Seal": "Master",
      "Proficiency": "Faith +3, Lance +3, Riding +3",
      "Abilities": "Canto, Terrain Resistance, White Tomefaire",
      "Mastery Abilities": "Defiant Res",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Mortal Savant",
      "Certification": "Sword A, Reason B+",
      "Level Seal": "Master",
      "Proficiency": "Reason +3, Sword +3",
      "Abilities": "Black Tomefaire, Swordfaire",
      "Mastery Abilities": "Warding Blow",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "War Master",
      "Certification": "Axe A, Brawl A",
      "Level Seal": "Master",
      "Proficiency": "Axe +3, Brawl +3",
      "Abilities": "Axefaire, Crit +20, Fistfaire",
      "Mastery Abilities": "Quick Riposte, War Master's Strike",
      "Magic": "No",
      "Specific": "Male only",
    },
    {
      "Class Name": "Wyvern Lord",
      "Certification": "Lance C, Axe A, Flying A",
      "Level Seal": "Master",
      "Proficiency": "Axe +3, Flying +3, Lance +3",
      "Abilities": "Avo +10, Axefaire, Canto",
      "Mastery Abilities": "Defiant Crit",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Armored Lord",
      "Certification": "Start of Chapter 13",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Axe +3, Hvy Armor +3",
      "Abilities": "Axefaire, Charm",
      "Mastery Abilities": "Pomp & Circumstance",
      "Magic": "No",
      "Specific": "Edelgard only",
    },
    {
      "Class Name": "Barbarossa",
      "Certification": "Start of Chapter 17",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Bow +3, Flying +3",
      "Abilities": "Bowfaire, Canto, Charm",
      "Mastery Abilities": "Wind God",
      "Magic": "No",
      "Specific": "Claude only",
    },
    {
      "Class Name": "Emperor",
      "Certification": "Start of Chapter 16",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Axe +3, Hvy Armor +3",
      "Abilities": "Axefaire, Charm",
      "Mastery Abilities": "Flickering Flower",
      "Magic": "No",
      "Specific": "Edelgard only",
    },
    {
      "Class Name": "Great Lord",
      "Certification": "Start of Chapter 16",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Lance +3, Sword +3",
      "Abilities": "Charm, Lancefaire",
      "Mastery Abilities": "Paraselene",
      "Magic": "No",
      "Specific": "Dimitri only",
    },
    {
      "Class Name": "High Lord",
      "Certification": "Start of Chapter 13",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Lance +3, Sword +3",
      "Abilities": "Charm, Lancefaire",
      "Mastery Abilities": "Pomp & Circumstance",
      "Magic": "No",
      "Specific": "Dimitri only",
    },
    {
      "Class Name": "Lord",
      "Certification": "Sword D+, Authority C",
      "Level Seal": "Lord",
      "Proficiency": "Authority +2, Lance +1, Sword +2",
      "Abilities": "Charm",
      "Mastery Abilities": "Resistance +2, Subdue",
      "Magic": "No",
      "Specific": "House Leaders only",
    },
    {
      "Class Name": "Wyvern Master",
      "Certification": "Start of Chapter 13",
      "Level Seal": "Lord",
      "Proficiency": "Authority +3, Bow +3, Flying +3",
      "Abilities": "Bowfaire, Canto, Charm",
      "Mastery Abilities": "Pomp & Circumstance",
      "Magic": "No",
      "Specific": "Claude only",
    },
    {
      "Class Name": "Commoner",
      "Certification": "Can use magic at half uses",
      "Level Seal": "Unique",
      "Proficiency": "",
      "Abilities": "",
      "Mastery Abilities": "HP +5",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Noble",
      "Certification": "Can use magic at half uses",
      "Level Seal": "Unique",
      "Proficiency": "",
      "Abilities": "",
      "Mastery Abilities": "HP +5",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Dancer",
      "Certification": "Win the White Heron Cup",
      "Level Seal": "Unique",
      "Proficiency": "Authority +2, Sword +2",
      "Abilities": "Dance",
      "Mastery Abilities": "Special Dance",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Enlightened One",
      "Certification": "Start of Chapter 11",
      "Level Seal": "Unique",
      "Proficiency": "Authority +3, Brawl +2, Faith +3, Sword +3",
      "Abilities": "Swordfaire, Terrain Resistance",
      "Mastery Abilities": "Sacred Power",
      "Magic": "Yes",
      "Specific": "Byleth only",
    },
    {
      "Class Name": "Archbishop",
      "Certification": "Can use magic",
      "Level Seal": "Unique",
      "Proficiency": "Authority +3, Faith +3, Sword +3",
      "Abilities": "Charm, Commander, Terrain Resistance",
      "Mastery Abilities": "Sacred Power",
      "Magic": "Yes",
      "Specific": "Rhea only",
    },
    {
      "Class Name": "Death Knight",
      "Certification": "Can use magic",
      "Level Seal": "",
      "Proficiency": "Lance +3, Reason +3, Riding +3",
      "Abilities": "Canto, Lancefaire",
      "Mastery Abilities": "Counterattack",
      "Magic": "Yes",
      "Specific": "Death Knight only",
    },
    {
      "Class Name": "Swordmaster",
      "Certification": "Sword A",
      "Level Seal": "Advanced",
      "Proficiency": "Sword +3",
      "Abilities": "Sword Critical +10, Swordfaire",
      "Mastery Abilities": "Astra",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Hero",
      "Certification": "Sword B, Axe C",
      "Level Seal": "Advanced",
      "Proficiency": "Axe +2, Sword +3",
      "Abilities": "Swordfaire, Vantage",
      "Mastery Abilities": "Defiant Str",
      "Magic": "No",
      "Specific": "Male only",
    },
    {
      "Class Name": "Assassin",
      "Certification": "Sword B, Bow C",
      "Level Seal": "Advanced",
      "Proficiency": "Bow +2, Sword +3",
      "Abilities": "Locktouch, Stealth, Swordfaire",
      "Mastery Abilities": "Assassinate, Lethality",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Paladin",
      "Certification": "Lance B, Riding B",
      "Level Seal": "Advanced",
      "Proficiency": "Lance +3, Riding +3, Sword +2",
      "Abilities": "Canto, Lancefaire, Terrain Resistance",
      "Mastery Abilities": "Aegis",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Warrior",
      "Certification": "Axe A",
      "Level Seal": "Advanced",
      "Proficiency": "Axe +3",
      "Abilities": "Axe Critical +10, Axefaire",
      "Mastery Abilities": "Wrath",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Fortress Knight",
      "Certification": "Axe B, Heavy Armor B",
      "Level Seal": "Advanced",
      "Proficiency": "Axe +3, Hvy Armor +3, Lance +2",
      "Abilities": "Axefaire, Weight -5",
      "Mastery Abilities": "Pavise",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Wyvern Rider",
      "Certification": "Axe B, Flying C",
      "Level Seal": "Advanced",
      "Proficiency": "Axe +3, Flying +3, Lance +2",
      "Abilities": "Axefaire, Canto",
      "Mastery Abilities": "Seal Defense",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Sniper",
      "Certification": "Bow A",
      "Level Seal": "Advanced",
      "Proficiency": "Bow +3",
      "Abilities": "Bowfaire, Bowrange +1",
      "Mastery Abilities": "Hunter's Volley",
      "Magic": "No",
      "Specific": "",
    },
    {
      "Class Name": "Grappler",
      "Certification": "Brawl A",
      "Level Seal": "Advanced",
      "Proficiency": "Brawl +3",
      "Abilities": "Fistfaire, Unarmed Combat",
      "Mastery Abilities": "Fierce Iron Fist, Tomebreaker",
      "Magic": "No",
      "Specific": "Male only",
    },
    {
      "Class Name": "Warlock",
      "Certification": "Reason A",
      "Level Seal": "Advanced",
      "Proficiency": "Faith +2, Reason +3",
      "Abilities": "Black Magic Uses x2, Black Tomefaire",
      "Mastery Abilities": "Bowbreaker",
      "Magic": "Yes",
      "Specific": "",
    },
    {
      "Class Name": "Dark Bishop",
      "Certification": "Reason A",
      "Level Seal": "Advanced",
      "Proficiency": "Faith +2, Reason +3",
      "Abilities": "Fiendish Blow, Heartseeker, Miasma",
      "Mastery Abilities": "Lifetaker",
      "Magic": "No",
      "Specific": "Male only, Dark Seal",
    },
    {
      "Class Name": "Bishop",
      "Certification": "Faith A",
      "Level Seal": "Advanced",
      "Proficiency": "Faith +3, Reason +2",
      "Abilities": "Terrain Resistance, White Magic Heal +10, White Magic Uses x2",
      "Mastery Abilities": "Renewal",
      "Magic": "Yes",
      "Specific": "",
    }
]

export { fireEmblemClasses }